plugins { id 'com.android.application' }

android {
    namespace 'br.com.professor100destino.docenciafacil'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.professor100destino.docenciafacil'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
    }
}
